name: Python Checks

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - main
      - prod

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black mypy pytest
        pip install types-requests types-beautifulsoup4

    - name: Configure mypy to ignore joblib and streamlit only
      run: |
        echo "[mypy]" > mypy.ini
        echo "ignore_missing_imports = False" >> mypy.ini
        echo "" >> mypy.ini
        echo "[mypy-joblib.*]" >> mypy.ini
        echo "ignore_missing_imports = True" >> mypy.ini
        echo "" >> mypy.ini
        echo "[mypy-streamlit.*]" >> mypy.ini
        echo "ignore_missing_imports = True" >> mypy.ini

    - name: Run pylint
      run: |
        pylint tests/

    - name: Run mypy
      run: |
        mypy .

    - name: Run pytest
      run: |
        pytest tests